### ISSUE TITLE
[Bug] k4: random hangups

### ISSUE THREAD

**Issue by dexter93** [dexter93/qmk_firmware#4]
Chip seems to lockup randomly in this implementation on k4 branch. Keyboard dies and a random row of led's lights up ( full or partially)

Temp solution can be found here 
https://github.com/dexter93/qmk_firmware/commit/a19d0141ac7014b8b6d05c5ff150f85d3c38fe5d

This is fixed in the k4_testing branch

**Comment by jedifindtrick** [comment]
I've noticed that as well. I also get random keys geting stuck or "reboots" when using different key combinations.

**Comment by stdvar** [comment]
also it is good to add debounce by separating   matrix scan from pwm led.
